/**
 * @typedef {{ role: 'interpreter' | 'builder' | 'fixer', messages: Array<{role: string, content: string}>, stream?: boolean }} CallModelOpts
 */

const CEREBRAS_BASE_URL = 'https://api.cerebras.ai'

export class ProviderError extends Error {
  constructor(publicMessage, options = {}) {
    super(options.logMessage || publicMessage)
    this.name = 'ProviderError'
    this.publicMessage = publicMessage
    this.statusCode = options.statusCode || 502
  }
}

/**
 * callModel({ role, messages, stream })
 *
 * PRE-BUILD placeholder: reads PROVIDER and MODEL from env.
 * If a real API key + base URL are set it will call an OpenAI-compatible endpoint.
 * Without credentials it falls back to deterministic mock responses.
 *
 * @param {CallModelOpts} opts
 * @returns {Promise<string> | AsyncIterable<string>}
 */
export async function callModel(opts) {
  const provider = resolveProvider()
  const model = resolveModel(provider)
  const apiKey = resolveApiKey(provider)
  const baseUrl = resolveBaseUrl(provider)

  // No real credentials → mock
  if (provider === 'mock' || !apiKey) {
    if (opts.stream) {
      return mockStreamResponse(opts.role)
    }

    return normalizeRoleOutput(opts.role, mockResponse(opts.role))
  }

  let res

  try {
    res = await fetch(buildChatCompletionsUrl(baseUrl), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: opts.messages,
        stream: !!opts.stream,
        max_tokens: 4096,
      }),
    })
  } catch (error) {
    throw new ProviderError('Unable to reach the model provider.', {
      logMessage: `callModel ${provider} network error: ${error instanceof Error ? error.message : String(error)}`,
    })
  }

  if (!res.ok) {
    const body = await res.text().catch(() => '')
    throw new ProviderError('The model provider returned an error.', {
      logMessage: `callModel ${provider} error ${res.status}: ${body.slice(0, 400)}`,
      statusCode: 502,
    })
  }

  if (opts.stream) {
    if (!res.body) {
      throw new ProviderError('The model provider did not return a stream body.', {
        logMessage: `callModel ${provider} stream missing response body`,
      })
    }

    return streamChunks(res.body)
  }

  const data = await res.json()
  return normalizeRoleOutput(opts.role, extractMessageContent(data))
}

function resolveProvider() {
  const explicit = (process.env.PROVIDER || '').trim().toLowerCase()
  if (explicit) {
    return explicit
  }

  if (process.env.CEREBRAS_API_KEY) {
    return 'cerebras'
  }

  if (process.env.MODEL_API_KEY) {
    return 'openai-compatible'
  }

  return 'mock'
}

function resolveModel(provider) {
  if (provider === 'cerebras') {
    return process.env.CEREBRAS_MODEL || process.env.MODEL || 'llama-3.3-70b'
  }

  return process.env.MODEL || 'mock-model'
}

function resolveApiKey(provider) {
  if (provider === 'cerebras') {
    return process.env.CEREBRAS_API_KEY || process.env.MODEL_API_KEY || ''
  }

  return process.env.MODEL_API_KEY || ''
}

function resolveBaseUrl(provider) {
  if (provider === 'cerebras') {
    return process.env.CEREBRAS_BASE_URL || process.env.MODEL_BASE_URL || CEREBRAS_BASE_URL
  }

  return process.env.MODEL_BASE_URL || ''
}

function buildChatCompletionsUrl(baseUrl) {
  const normalized = (baseUrl || '').replace(/\/+$/, '')

  if (/\/v\d+$/i.test(normalized)) {
    return `${normalized}/chat/completions`
  }

  return `${normalized}/v1/chat/completions`
}

/**
 * Mock responses keyed by role for PRE-BUILD demos.
 */
function mockResponse(role) {
  const mocks = {
    interpreter: JSON.stringify({
      app_name: 'Demo App',
      description: 'A generated demo app',
      components: ['display:hello', 'button:Say hi'],
      logic: 'Show a small welcome app with one display and one button.',
      window_size: 'medium',
    }),
    builder: `<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Inter,system-ui,sans-serif;background:#070b1a;color:#e6ebff;padding:24px}.card{border:1px solid #243056;background:rgba(18,26,51,.8);border-radius:12px;padding:16px}</style></head><body><div class="card"><h1 class="praxis-display">Demo App</h1><p>Generated by Praxis (mock builder)</p></div></body></html>`,
    fixer: `<!doctype html><html><head><meta charset="utf-8"></head><body><p>Fixed by mock fixer</p></body></html>`,
  }
  return mocks[role] ?? ''
}

async function* mockStreamResponse(role) {
  const text = normalizeRoleOutput(role, mockResponse(role))
  const step = Math.max(32, Math.floor(text.length / 8))

  for (let i = 0; i < text.length; i += step) {
    yield text.slice(i, i + step)
  }
}

/**
 * Naive SSE chunk reader for streaming. Normalizes provider differences.
 */
async function* streamChunks(body) {
  const reader = body.getReader()
  const decoder = new TextDecoder()
  let buf = ''

  try {
    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      buf += decoder.decode(value, { stream: true })
      const lines = buf.split('\n')
      buf = lines.pop() ?? ''
      for (const line of lines) {
        const trimmed = line.replace(/^data:\s*/, '')
        if (!trimmed || trimmed === '[DONE]') continue
        try {
          const parsed = JSON.parse(trimmed)
          const delta = extractContentText(parsed.choices?.[0]?.delta?.content)
          if (delta) yield delta
        } catch {
          // non-JSON line, skip
        }
      }
    }
  } finally {
    reader.releaseLock()
  }
}

function extractMessageContent(data) {
  return extractContentText(data?.choices?.[0]?.message?.content)
}

function extractContentText(content) {
  if (typeof content === 'string') {
    return content
  }

  if (Array.isArray(content)) {
    return content
      .map((part) => {
        if (typeof part === 'string') return part
        if (part && typeof part.text === 'string') return part.text
        return ''
      })
      .join('')
  }

  return ''
}

export function normalizeRoleOutput(role, raw) {
  const text = String(raw || '').trim()

  if (role === 'builder' || role === 'fixer') {
    return normalizeHtml(text)
  }

  if (role === 'interpreter') {
    return normalizeJson(text)
  }

  return text
}

function normalizeHtml(text) {
  const lower = text.toLowerCase()
  const doctypeIndex = lower.indexOf('<!doctype html>')
  const htmlIndex = lower.indexOf('<html')
  const startIndex = doctypeIndex >= 0 ? doctypeIndex : htmlIndex
  const endIndex = lower.lastIndexOf('</html>')

  if (startIndex >= 0 && endIndex >= 0 && endIndex > startIndex) {
    return text.slice(startIndex, endIndex + '</html>'.length).trim()
  }

  return text
}

function normalizeJson(text) {
  const startIndex = text.indexOf('{')
  const endIndex = text.lastIndexOf('}')

  if (startIndex >= 0 && endIndex > startIndex) {
    return text.slice(startIndex, endIndex + 1).trim()
  }

  return text
}
