/**
 * @typedef {{ role: 'interpreter' | 'builder' | 'fixer', messages: Array<{role: string, content: string}>, stream?: boolean }} CallModelOpts
 */

/**
 * callModel({ role, messages, stream })
 *
 * PRE-BUILD placeholder: reads PROVIDER and MODEL from env.
 * If a real API key + base URL are set it will call an OpenAI-compatible endpoint.
 * Without credentials it falls back to deterministic mock responses.
 *
 * @param {CallModelOpts} opts
 * @returns {Promise<string> | AsyncIterable<string>}
 */
export async function callModel(opts) {
  const provider = process.env.PROVIDER || 'mock'
  const model = process.env.MODEL || 'mock-model'
  const apiKey = process.env.MODEL_API_KEY || ''
  const baseUrl = process.env.MODEL_BASE_URL || ''

  // No real credentials → mock
  if (provider === 'mock' || !apiKey) {
    return mockResponse(opts.role)
  }

  // Real OpenAI-compatible call
  const res = await fetch(`${baseUrl.replace(/\/+$/, '')}/v1/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: opts.messages,
      stream: !!opts.stream,
      max_tokens: 4096,
    }),
  })

  if (!res.ok) {
    const body = await res.text().catch(() => '')
    throw new Error(`callModel ${provider} error ${res.status}: ${body.slice(0, 200)}`)
  }

  if (opts.stream) {
    return streamChunks(res.body)
  }

  const data = await res.json()
  return data.choices?.[0]?.message?.content ?? ''
}

/**
 * Mock responses keyed by role for PRE-BUILD demos.
 */
function mockResponse(role) {
  const mocks = {
    interpreter: JSON.stringify({
      name: 'Demo App',
      purpose: 'A generated demo app',
      components: [{ name: 'Hero', kind: 'section', description: 'Welcome banner' }],
    }),
    builder: `<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Inter,system-ui,sans-serif;background:#070b1a;color:#e6ebff;padding:24px}.card{border:1px solid #243056;background:rgba(18,26,51,.8);border-radius:12px;padding:16px}</style></head><body><div class="card"><h1 class="praxis-display">Demo App</h1><p>Generated by Praxis (mock builder)</p></div></body></html>`,
    fixer: `<!doctype html><html><head><meta charset="utf-8"></head><body><p>Fixed by mock fixer</p></body></html>`,
  }
  return mocks[role] ?? ''
}

/**
 * Naive SSE chunk reader for streaming. Normalizes provider differences.
 */
async function* streamChunks(body) {
  const reader = body.getReader()
  const decoder = new TextDecoder()
  let buf = ''

  try {
    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      buf += decoder.decode(value, { stream: true })
      const lines = buf.split('\n')
      buf = lines.pop() ?? ''
      for (const line of lines) {
        const trimmed = line.replace(/^data:\s*/, '')
        if (!trimmed || trimmed === '[DONE]') continue
        try {
          const parsed = JSON.parse(trimmed)
          const delta = parsed.choices?.[0]?.delta?.content
          if (delta) yield delta
        } catch {
          // non-JSON line, skip
        }
      }
    }
  } finally {
    reader.releaseLock()
  }
}
